const constants = {
  GETCATEGORIES: "GET_CATEGOREIS",
  GETUNIVERSITIES: "GET_UNIVERSITIES",
  SETCOMPARE: "SET_COMPARE",
  REMOVECOMPARE: "REMOVE_COMPARE",
  REMOVEALLCOMPARE: "REMOVE_ALL_COMPARE",
  SETMINIMISZED: "SET_MINIMISZED",
};

export default constants;
